
name: Build and Push User Service Image

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push user-service image (multi-arch)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/user-service:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/user-service:${{ github.run_number }}
      
      - name: Update image tag in k8s-microservices-helm values.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git clone https://x-access-token:${GITHUB_TOKEN}@github.com/urveshnimavat/k8s-microservices-helm.git
          cd k8s-microservices-helm
          yq e '.userService.image = "docker.io/urveshnimavat57/user-service:${{ github.run_number }}"' -i values.yaml
          git add values.yaml
          git commit -m "chore: update userService image tag to ${{ github.run_number }} [ci skip]"
          git push
